### ISSUE TITLE
Who is doing the restaraunt app?

### ISSUE THREAD

**Issue by de-sh** [agzuniverse/angelhack#1]
This might be irrelevant, but are you doing the restaraunt app, cause the source code points in the direction of a registry for school students... BTW you guys could also have used the ability ot make a private repo in gitlab. XD

**Comment by de-sh** [comment]
This might be a good idea, or a lame one... but hey @agzuniverse, we could actually use your help. Just say you aren't able to come to H4T, you could sit at home and help us... ;)

**Comment by de-sh** [comment]
Guys, the f**k? This is still open :joy:

**Comment by agzuniverse** [comment]
Not anymore.
